services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000" # Standard Grafana access port
    user: "1001"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    env_file:
      - ./.env
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_LOG_LEVEL=${GF_LOG_LEVEL}
      - GF_SMTP_ENABLED=${GF_SMTP_ENABLED}
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_STARTTLS_POLICY=${GF_SMTP_STARTTLS_POLICY}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}

    restart: unless-stopped
    networks:
      - loki_net

networks:
  loki_net:
    driver: bridge

volumes:
  grafana-data:
